import { useTranslation } from "react-i18next";
import { useSetupProjects } from "../Projects/hooks/useSetupProjects";

const EMAIL_ADDRESS = "developerandreo@gmail.com";
const SPOTIFY_PROFILE_URL = "https://open.spotify.com/user/lyixkn1qhupjuexfkygpbzmnd";

export function usePortfolioContent() {
  const { i18n, t } = useTranslation();
  const projects = useSetupProjects();

  const text = i18n.language?.startsWith("pt") ? {
    aboutLabel: "sobre",
    availabilityBody:
      "Estou aberto a freelas, oportunidades remotas e produtos que precisam de uma camada visual mais forte com melhores decisões de UX.",
    availabilityLabel: "disponível para novos projetos",
    availabilityTitle: "Produto, clareza e identidade visual no mesmo build.",
    connectLabel: "conectar",
    contactDescription:
      "Se você quer lançar uma ideia, melhorar uma interface existente ou dar mais personalidade a um produto, vou gostar de ouvir sobre isso.",
    contactEyebrow: "contato",
    contactTitleAccent: "vamos",
    contactTitleRest: "conversar",
    scheduleCta: "agendar conversa",
    scheduleDescription:
      "Estou aberto a trabalho.",
    scheduleEyebrow: "disponibilidade",
    scheduleTitleAccent: "aberto",
    scheduleTitleRest: "a trabalho",
    scheduleTrailing: "Vamos conversar.",
    copiedEmail: "email copiado",
    copyEmail: "copiar email",
    emailLabel: "email",
    experienceRange: "2025 - 2026",
    experienceTitleAccent: "Experiência",
    experienceTitleRest: "& cargos",
    formError: "Não consegui enviar agora. Tente novamente em instantes.",
    formMessageLabel: "mensagem",
    formNameLabel: "nome",
    formSending: "enviando...",
    formSubmit: "enviar mensagem",
    formSuccess: "Mensagem enviada com sucesso. Obrigado pelo contato.",
    heroLead: "criando interfaces que as pessoas",
    heroLeadHighlight: "querem usar.",
    heroRoleAccent: "desenvolvedor",
    heroRoleRest: "full-stack",
    methodsLabel: "formas de contato",
    projectsTitleRest: "em destaque",
    primaryCta: "ver currículo",
    secondaryCta: "ver contato",
    summary:
      "Full Stack Software Engineer com experiência no desenvolvimento de plataformas financeiras, aplicações SaaS e sistemas web escaláveis.",
    spotifyFallbackMessage: "A atividade do Spotify está indisponível no momento.",
    spotifyLabel: "ouvindo",
    spotifyPlayedAtPrefix: "tocada às",
    spotifyPlayingLabel: "tocando agora",
    spotifyProfileLabel: "abrir perfil",
    spotifyRecentLabel: "última faixa",
    spotifyTitleAccent: "atividade",
    spotifyTitleRest: "Spotify",
    spotifyTrackLinkLabel: "abrir música",
    toolLabel: "ferramentas",
    viewAllProjects: "ver projetos",
    workModeBody:
      "Meu processo equilibra produto, implementação escalável e usabilidade real. Gosto de software limpo, rápido e intencional.",
    workModeLabel: "como eu trabalho",
  } : {
    aboutLabel: "about",
    availabilityBody:
      "I am open to freelance work, remote opportunities, and products that need a stronger visual layer with better UX decisions.",
    availabilityLabel: "available for new projects",
    availabilityTitle: "Product thinking, clarity, and visual identity in the same build.",
    connectLabel: "connect",
    contactDescription:
      "If you want to launch an idea, improve an existing interface, or shape a portfolio with more personality, I would love to hear about it.",
    contactEyebrow: "contact",
    contactTitleAccent: "let's",
    contactTitleRest: "talk",
    scheduleCta: "schedule a meeting",
    scheduleDescription:
      "I'm open to work.",
    scheduleEyebrow: "availability",
    scheduleTitleAccent: "open",
    scheduleTitleRest: "to work",
    scheduleTrailing: "Let's talk.",
    copiedEmail: "email copied",
    copyEmail: "copy email",
    emailLabel: "email",
    experienceRange: "2025 - 2026",
    experienceTitleAccent: "Experience",
    experienceTitleRest: "& roles",
    formError: "I could not send it right now. Please try again in a moment.",
    formMessageLabel: "message",
    formNameLabel: "name",
    formSending: "sending...",
    formSubmit: "send message",
    formSuccess: "Message sent successfully. Thanks for reaching out.",
    heroLead: "building interfaces people",
    heroLeadHighlight: "want to use.",
    heroRoleAccent: "full-stack",
    heroRoleRest: "developer",
    methodsLabel: "ways to reach me",
    projectsTitleAccent: "featured",
    projectsTitleRest: "projects",
    primaryCta: "view resume",
    secondaryCta: "view contact",
    summary:
      "Full Stack Software Engineer with experience developing financial platforms, SaaS applications, and scalable web systems.",
    spotifyFallbackMessage: "Spotify activity is unavailable right now.",
    spotifyLabel: "listening",
    spotifyPlayedAtPrefix: "played at",
    spotifyPlayingLabel: "now playing",
    spotifyProfileLabel: "open profile",
    spotifyRecentLabel: "last played",
    spotifyTitleAccent: "Spotify",
    spotifyTitleRest: "activity",
    spotifyTrackLinkLabel: "open track",
    toolLabel: "toolbox",
    viewAllProjects: "view all projects",
    workModeBody:
      "My process usually balances product thinking, scalable implementation, and real usability concerns. I like software that feels clean, fast, and intentional from end to end.",
    workModeLabel: "how I work",
  };

  return {
    aboutBody: t("About.sobre"),
    connectLinks: [
      {
        description: "repos, experiments, and code",
        href: t("Socials.Github"),
        label: "github",
        value: "andreodev",
      },
      {
        description: "career path and experience",
        href: t("Socials.Linkedin"),
        label: "linkedin",
        value: "andreo-henrique",
      },
      {
        description: "behind the scenes and updates",
        href: t("Socials.Instagram"),
        label: "instagram",
        value: "@andreodevv",
      },
    ],
    contactCopy: {
      description: text.contactDescription,
      titleAccent: text.contactTitleAccent,
      titleRest: text.contactTitleRest,
    },
    scheduleCopy: {
      availabilityBody: text.availabilityBody,
      availabilityLabel: text.availabilityLabel,
      availabilityTitle: text.availabilityTitle,
      cta: text.scheduleCta,
      description: text.scheduleDescription,
      eyebrow: text.scheduleEyebrow,
      titleAccent: text.scheduleTitleAccent,
      trailing: text.scheduleTrailing,
      titleRest: text.scheduleTitleRest,
    },
    copiedEmailLabel: text.copiedEmail,
    copyEmailLabel: text.copyEmail,
    currentTools: [
      "React",
      "React Native",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Go",
      "Tailwind CSS",
      "Docker",
      "Redis",
      "MongoDB",
      "SQL",
    ],
    emailAddress: EMAIL_ADDRESS,
    emailLabel: text.emailLabel,
    emailHref: t("Socials.Gmail"),
    experience: {
      items: [
        {
          company: "AutoCore White Label",
          details: [
            "Founder-led SaaS white-label platform for automotive workshop management, built as a personal product with multi-tenant architecture, isolated data, custom branding, and per-operation settings.",
            "Responsible for product ideation, business requirements, architecture, frontend, backend, authentication, permissions, infrastructure, deployment, and business rules.",
            "Structured more than 8 business modules, including customers, vehicles, service orders, quotes, inventory, finance, POS, commissions, and administrative settings.",
            "Built complete flows connecting quote, service order, sale, financial control, stock deduction, and commission calculation.",
            "Implemented Resend for automated transactional emails and developed a Google Chrome extension integrated with the platform ecosystem.",
          ],
          location: "Brazil · Remote",
          period: "MAY 2026 - PRESENT",
          role: "Founder & Full Stack Software Engineer",
          stack: ["React", "Next.js", "TypeScript", "Go", "PostgreSQL", "Multi-Tenant"],
          type: "Personal project",
        },
        {
          company: "Wite Group",
          details: [
            "Develop full-stack features for a financial ecosystem that includes marketplace, payment gateway, Pix, BaaS, white-label systems, and dashboards.",
            "Build modern interfaces with React.js and TypeScript, integrated with scalable REST APIs built with Node.js, NestJS, and TypeScript.",
            "Implement business rules, service layers, database integrations, and external API connections to keep platform data consistent and reliable.",
            "Evolve critical modules such as product management, payment links, integrations, transaction processing, and admin dashboards.",
            "Improve frontend and backend architecture through reusable components, standardized API communication, and maintainable domain layers.",
          ],
          location: "Rio de Janeiro, Brazil · Remote",
          period: "JUL 2025 - PRESENT",
          role: "Full Stack Software Developer",
          stack: ["React.js", "Node.js", "NestJS", "TypeScript", "REST APIs", "White-label", "BaaS"],
          type: "Full-time",
        },
        {
          company: "InovStar Atendimento",
          details: [
            "Worked on the development of web applications and backend APIs for internal systems and digital platforms.",
            "Developed backend services with Node.js and TypeScript, structuring routes, business rules, and database integrations.",
            "Implemented a chat system integrated with the WhatsApp API to support real-time communication.",
            "Contributed to web interfaces in React.js, integrating the frontend with REST APIs for data consumption and manipulation.",
            "Worked with MongoDB data modeling and manipulation to keep information organized and efficient.",
            "Supported new feature delivery and ongoing maintenance using Git-based collaboration workflows.",
          ],
          location: "Minas Gerais, Brazil · Remote",
          period: "JUL 2025 - OCT 2025",
          role: "Full-Stack Developer",
          stack: ["React.js", "Node.js", "TypeScript", "MongoDB", "WhatsApp API", "REST APIs"],
          type: "Freelance",
        },
        {
          company: "Planno Finanças",
          details: [
            "Implemented more than 15 frontend features with Vue.js and React.js, improving user experience through feedback-driven iterations.",
            "Integrated more than 10 REST APIs with the backend team, reducing data loading time and improving application responsiveness.",
            "Contributed to biweekly agile sprints, helping maintain strong on-time delivery and team efficiency.",
            "Fixed more than 40 bugs and refactored critical modules, increasing test coverage and reducing production issues.",
          ],
          location: "Remote",
          period: "MAY 2025 - JUL 2025",
          role: "Full Stack Developer Intern",
          stack: ["Vue.js", "React.js", "REST APIs", "Agile", "Bug Fixing", "Refactoring"],
          type: "Internship",
        },
      ],
      label: text.experienceLabel,
      range: text.experienceRange,
      titleAccent: text.experienceTitleAccent,
      titleRest: text.experienceTitleRest,
    },
    formLabels: {
      email: text.emailLabel,
      error: text.formError,
      message: text.formMessageLabel,
      name: text.formNameLabel,
      sending: text.formSending,
      submit: text.formSubmit,
      success: text.formSuccess,
    },
    hero: {
      lead: text.heroLead,
      leadHighlight: text.heroLeadHighlight,
      mascotLabel: "Interactive cat",
      name: t("Info.name"),
      note: "click the mascot",
      roleAccent: text.heroRoleAccent,
      roleRest: text.heroRoleRest,
      status: t("Info.ativo"),
    },
    introSummary: text.summary,
    methodsLabel: text.methodsLabel,
    pageHeadings: {
      projects: {
        accent: text.projectsPageAccent,
        description: text.projectsDescription,
        rest: text.projectsPageRest,
      },
    },
    primaryCtaLabel: text.primaryCta,
    projects,
    projectsTitle: {
      accent: text.projectsTitleAccent,
      rest: text.projectsTitleRest,
    },
    resumeHref: "/andreo_henrique_CV_PT.pdf",
    secondaryCtaLabel: text.secondaryCta,
    sectionLabels: {
      about: text.aboutLabel,
      connect: text.connectLabel,
      contact: text.contactEyebrow,
      projects: text.projectsLabel,
      spotify: text.spotifyLabel,
      tools: text.toolLabel,
    },
    spotify: {
      description: text.spotifyDescription,
      fallbackMessage: text.spotifyFallbackMessage,
      label: text.spotifyLabel,
      playedAtPrefix: text.spotifyPlayedAtPrefix,
      playingLabel: text.spotifyPlayingLabel,
      profileHref: SPOTIFY_PROFILE_URL,
      profileLabel: text.spotifyProfileLabel,
      recentLabel: text.spotifyRecentLabel,
      titleAccent: text.spotifyTitleAccent,
      titleRest: text.spotifyTitleRest,
      trackLinkLabel: text.spotifyTrackLinkLabel,
    },
    toolDescription: text.workModeBody,
    viewAllProjectsLabel: text.viewAllProjects,
    workAvailability: {
      body: text.availabilityBody,
      label: text.availabilityLabel,
      title: text.availabilityTitle,
    },
  };
}
