import { useTranslation } from "react-i18next";
import { useSetupProjects } from "../Projects/hooks/useSetupProjects";

const EMAIL_ADDRESS = "developerandreo@gmail.com";
const SPOTIFY_PROFILE_URL = "https://open.spotify.com/user/lyixkn1qhupjuexfkygpbzmnd";

export function usePortfolioContent() {
  const { t } = useTranslation();
  const projects = useSetupProjects();

  const text = {
    aboutLabel: "about",
    availabilityBody:
      "I am open to freelance work, remote opportunities, and products that need a stronger visual layer with better UX decisions.",
    availabilityLabel: "available for new projects",
    availabilityTitle: "Product thinking, clarity, and visual identity in the same build.",
    connectLabel: "connect",
    contactDescription:
      "If you want to launch an idea, improve an existing interface, or shape a portfolio with more personality, I would love to hear about it.",
    contactEyebrow: "contact",
    contactTitleAccent: "let's",
    contactTitleRest: "talk",
    copiedEmail: "email copied",
    copyEmail: "copy email",
    emailLabel: "email",
    experienceLabel: "career path",
    experienceRange: "2025 - 2026",
    experienceTitleAccent: "Experience",
    experienceTitleRest: "& roles",
    formError: "I could not send it right now. Please try again in a moment.",
    formMessageLabel: "message",
    formNameLabel: "name",
    formSending: "sending...",
    formSubmit: "send message",
    formSuccess: "Message sent successfully. Thanks for reaching out.",
    heroLead: "building interfaces people",
    heroLeadHighlight: "want to use.",
    heroRoleAccent: "full-stack",
    heroRoleRest: "developer",
    methodsLabel: "ways to reach me",
    projectsDescription:
      "A curated mix of real work and visual experiments focused on interface design, product thinking, and performance.",
    projectsLabel: "work",
    projectsPageAccent: "selected",
    projectsPageRest: "projects",
    projectsTitleAccent: "featured",
    projectsTitleRest: "projects",
    primaryCta: "view resume",
    secondaryCta: "view contact",
    summary:
      "Frontend Software Engineer focused on code quality, scalability, performance, and user experience.",
    spotifyDescription:
      "A live glimpse of what is playing right now, or the most recent track when the player is idle.",
    spotifyFallbackMessage: "Spotify activity is unavailable right now.",
    spotifyLabel: "listening",
    spotifyPlayedAtPrefix: "played at",
    spotifyPlayingLabel: "now playing",
    spotifyProfileLabel: "open profile",
    spotifyRecentLabel: "last played",
    spotifyTitleAccent: "Spotify",
    spotifyTitleRest: "activity",
    spotifyTrackLinkLabel: "open track",
    toolLabel: "toolbox",
    viewAllProjects: "view all projects",
    workModeBody:
      "My process usually balances visual exploration, component systems, and real usability concerns. I like interfaces that feel clean, fast, and intentional.",
    workModeLabel: "how I work",
  };

  return {
    aboutBody: t("About.sobre"),
    connectLinks: [
      {
        description: "repos, experiments, and code",
        href: t("Socials.Github"),
        label: "github",
        value: "andreodev",
      },
      {
        description: "career path and experience",
        href: t("Socials.Linkedin"),
        label: "linkedin",
        value: "andreo-henrique",
      },
      {
        description: "behind the scenes and updates",
        href: t("Socials.Instagram"),
        label: "instagram",
        value: "@andreowdev",
      },
    ],
    contactCopy: {
      description: text.contactDescription,
      titleAccent: text.contactTitleAccent,
      titleRest: text.contactTitleRest,
    },
    copiedEmailLabel: text.copiedEmail,
    copyEmailLabel: text.copyEmail,
    currentTools: [
      "React",
      "React Native",
      "TypeScript",
      "Next.js",
      "Node.js",
      "Tailwind CSS",
      "MongoDB",
      "SQL",
    ],
    emailAddress: EMAIL_ADDRESS,
    emailLabel: text.emailLabel,
    emailHref: t("Socials.Gmail"),
    experience: {
      items: [
        {
          company: "Wite Group",
          details: [
            "Develop backend services for a financial platform covering marketplace, payment gateway, Pix, BaaS, and financial dashboards.",
            "Build scalable REST APIs with Node.js, NestJS, and TypeScript, implementing business rules across service layers.",
            "Integrate backend services with databases and external APIs to keep platform data consistent and reliable.",
            "Contribute to backend architecture improvements by structuring services, controllers, and domain layers for easier maintenance.",
            "Evolve critical modules such as product management, payment links, integrations, and transaction processing.",
            "Collaborate with frontend applications to improve API performance and standardize communication between systems.",
          ],
          location: "Rio de Janeiro, Brazil · Remote",
          period: "FEB 2026 - PRESENT",
          role: "Full Stack Software Developer",
          stack: ["Node.js", "NestJS", "TypeScript", "REST APIs", "Pix", "BaaS"],
          type: "Full-time",
        },
        {
          company: "Wite Group",
          details: [
            "Develop frontend interfaces and platform features for a financial ecosystem that includes marketplace, payment gateway, Pix, BaaS, and dashboards.",
            "Build modern interfaces and reusable components with React.js, TypeScript, and scalable frontend architecture practices.",
            "Implement new frontend functionality integrated with REST APIs, ensuring consistent and reliable data display.",
            "Improve frontend architecture and component standardization to accelerate delivery and streamline workflows.",
            "Evolve admin dashboards and management flows related to products, payment links, and platform operations.",
          ],
          location: "Rio de Janeiro, Brazil · Remote",
          period: "JUL 2025 - PRESENT",
          role: "Frontend Software Engineer",
          stack: ["React.js", "TypeScript", "REST APIs", "Dashboards", "Marketplace", "BaaS"],
          type: "Full-time",
        },
        {
          company: "InovStar Atendimento",
          details: [
            "Worked on the development of web applications and backend APIs for internal systems and digital platforms.",
            "Developed backend services with Node.js and TypeScript, structuring routes, business rules, and database integrations.",
            "Implemented a chat system integrated with the WhatsApp API to support real-time communication.",
            "Contributed to web interfaces in React.js, integrating the frontend with REST APIs for data consumption and manipulation.",
            "Worked with MongoDB data modeling and manipulation to keep information organized and efficient.",
            "Supported new feature delivery and ongoing maintenance using Git-based collaboration workflows.",
          ],
          location: "Minas Gerais, Brazil · Remote",
          period: "JUL 2025 - OCT 2025",
          role: "Full-Stack Developer",
          stack: ["React.js", "Node.js", "TypeScript", "MongoDB", "WhatsApp API", "REST APIs"],
          type: "Freelance",
        },
        {
          company: "Planno Finanças",
          details: [
            "Implemented more than 15 frontend features with Vue.js and React.js, improving user experience through feedback-driven iterations.",
            "Integrated more than 10 REST APIs with the backend team, reducing data loading time and improving application responsiveness.",
            "Contributed to biweekly agile sprints, helping maintain strong on-time delivery and team efficiency.",
            "Fixed more than 40 bugs and refactored critical modules, increasing test coverage and reducing production issues.",
          ],
          location: "Remote",
          period: "MAY 2025 - JUL 2025",
          role: "Full Stack Developer Intern",
          stack: ["Vue.js", "React.js", "REST APIs", "Agile", "Bug Fixing", "Refactoring"],
          type: "Internship",
        },
      ],
      label: text.experienceLabel,
      range: text.experienceRange,
      titleAccent: text.experienceTitleAccent,
      titleRest: text.experienceTitleRest,
    },
    formLabels: {
      email: text.emailLabel,
      error: text.formError,
      message: text.formMessageLabel,
      name: text.formNameLabel,
      sending: text.formSending,
      submit: text.formSubmit,
      success: text.formSuccess,
    },
    hero: {
      lead: text.heroLead,
      leadHighlight: text.heroLeadHighlight,
      mascotLabel: "Interactive cat",
      name: t("Info.name"),
      note: "click the mascot",
      roleAccent: text.heroRoleAccent,
      roleRest: text.heroRoleRest,
      status: t("Info.ativo"),
    },
    introSummary: text.summary,
    methodsLabel: text.methodsLabel,
    pageHeadings: {
      projects: {
        accent: text.projectsPageAccent,
        description: text.projectsDescription,
        rest: text.projectsPageRest,
      },
    },
    primaryCtaLabel: text.primaryCta,
    projects,
    projectsTitle: {
      accent: text.projectsTitleAccent,
      rest: text.projectsTitleRest,
    },
    resumeHref: "/andreo_henrique_CV_PT.pdf",
    secondaryCtaLabel: text.secondaryCta,
    sectionLabels: {
      about: text.aboutLabel,
      connect: text.connectLabel,
      contact: text.contactEyebrow,
      projects: text.projectsLabel,
      spotify: text.spotifyLabel,
      tools: text.toolLabel,
      workflow: text.workModeLabel,
    },
    spotify: {
      description: text.spotifyDescription,
      fallbackMessage: text.spotifyFallbackMessage,
      label: text.spotifyLabel,
      playedAtPrefix: text.spotifyPlayedAtPrefix,
      playingLabel: text.spotifyPlayingLabel,
      profileHref: SPOTIFY_PROFILE_URL,
      profileLabel: text.spotifyProfileLabel,
      recentLabel: text.spotifyRecentLabel,
      titleAccent: text.spotifyTitleAccent,
      titleRest: text.spotifyTitleRest,
      trackLinkLabel: text.spotifyTrackLinkLabel,
    },
    toolDescription: text.workModeBody,
    viewAllProjectsLabel: text.viewAllProjects,
    workAvailability: {
      body: text.availabilityBody,
      label: text.availabilityLabel,
      title: text.availabilityTitle,
    },
  };
}
